# This workflow will do a clean install of node dependencies and build the HMI source code
name: HMI build check

on:
  push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    # Npm build
    - name: Use Node version 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    # Backend server start check
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Init Submodules
      run: git -C ${{ github.workspace }} submodule update --init --recursive
    - name: Test Backend server startup
      run: timeout -s SIGINT 30s ./deploy_server.sh